@ECHO OFF

ECHO CCGUIMemDev.BAT:     Compiling GUI\MemDev

CALL CC GUIDEV
CALL CC GUIDEV_1
CALL CC GUIDEV_8
CALL CC GUIDEV_16
CALL CC GUIDEV_AA
CALL CC GUIDEV_Auto
CALL CC GUIDEV_Banding
CALL CC GUIDEV_Clear
CALL CC GUIDEV_CmpWithLCD
CALL CC GUIDEV_CopyFromLCD
CALL CC GUIDEV_CreateFixed
CALL CC GUIDEV_GetDataPtr
CALL CC GUIDEV_GetXSize
CALL CC GUIDEV_GetYSize
CALL CC GUIDEV_Measure
CALL CC GUIDEV_ReduceYSize
CALL CC GUIDEV_SetOrg
CALL CC GUIDEV_Usage
CALL CC GUIDEV_UsageBM
CALL CC GUIDEV_Write
CALL CC GUIDEV_WriteAlpha
CALL CC GUIDEV_WriteEx
CALL CC GUIDEV_XY2PTR
