#include "msp430f5438a.h"
#include "GPIO.h"

void Init_GPIO(void)
{
  KEY1_PULLUP;//上拉使能
  KEY2_PULLUP;
  KEY3_PULLUP;
  KEY4_PULLUP;
  KEY5_PULLUP;
  
  KEY1_OUT_H;//输出高，使得KEY1~KEY5输入上拉电阻使能
  KEY2_OUT_H;
  KEY3_OUT_H;
  KEY4_OUT_H;
  KEY5_OUT_H;
  
  LED1_DIROUT;//LED1~LED4设置为输出
  LED2_DIROUT;
  LED3_DIROUT;
  LED4_DIROUT;
  LED1_OFF;//初始化LED1~LED4熄灭
  LED2_OFF;
  LED3_OFF;
  LED4_OFF;
  
  BUZZER_DIROUT;//初始化BUZZER位输出
}