REM ****************************************
REM   Compile GUIDemo modules
REM ****************************************

CALL CC GUIDEMO
CALL CC GUIDEMO_Automotive
CALL CC GUIDEMO_Bitmap
CALL CC GUIDEMO_Bitmap4bpp
CALL CC GUIDEMO_Circle
CALL CC GUIDEMO_ColorBar
CALL CC GUIDEMO_ColorList
CALL CC GUIDEMO_Cursor
CALL CC GUIDEMO_Dialog
CALL CC GUIDEMO_Font
CALL CC GUIDEMO_FrameWin
CALL CC GUIDEMO_Graph
CALL CC GUIDEMO_HardwareInfo
CALL CC GUIDEMO_Intro
CALL CC GUIDEMO_LUT
CALL CC GUIDEMO_MemDevB
CALL CC GUIDEMO_Navi
CALL CC GUIDEMO_Polygon
CALL CC GUIDEMO_ProgBar
CALL CC GUIDEMO_Speed
CALL CC GUIDEMO_Touch
CALL CC SeggerLogoBlue
