@ECHO OFF

ECHO CCWM.BAT:            Compiling GUI\WM

CALL CC WM
CALL CC WM__ForEachDesc
CALL CC WM__GetFirstSibling
CALL CC WM__GetFocussedChild
CALL CC WM__GetLastSibling
CALL CC WM__GetOrg_AA
CALL CC WM__GetPrevSibling
CALL CC WM__IsAncestor
CALL CC WM__IsChild
CALL CC WM__IsEnabled
CALL CC WM__NotifyVisChanged
CALL CC WM__Screen2Client
CALL CC WM__SendMessage
CALL CC WM__SendMessageIfEnabled
CALL CC WM__SendMessageNoPara
CALL CC WM__UpdateChildPositions
CALL CC WM_AttachWindow
CALL CC WM_BringToBottom
CALL CC WM_BringToTop
CALL CC WM_Broadcast
CALL CC WM_CheckScrollPos
CALL CC WM_CriticalHandle
CALL CC WM_DIAG
CALL CC WM_EnableWindow
CALL CC WM_ForEachDesc
CALL CC WM_GetBkColor
CALL CC WM_GetClientRect
CALL CC WM_GetClientWindow
CALL CC WM_GetDesktopWindow
CALL CC WM_GetDesktopWindowEx
CALL CC WM_GetDiagInfo
CALL CC WM_GetDialogItem
CALL CC WM_GetFirstChild
CALL CC WM_GetFlags
CALL CC WM_GetFocussedWindow
CALL CC WM_GetId
CALL CC WM_GetInsideRect
CALL CC WM_GetInsideRectExScrollbar
CALL CC WM_GetInvalidRect
CALL CC WM_GetNextSibling
CALL CC WM_GetOrg
CALL CC WM_GetParent
CALL CC WM_GetPrevSibling
CALL CC WM_GetScrollbar
CALL CC WM_GetScrollPartner
CALL CC WM_GetScrollState
CALL CC WM_GetWindowRect
CALL CC WM_GetWindowSize
CALL CC WM_HasCaptured
CALL CC WM_HasFocus
CALL CC WM_Hide
CALL CC WM_IsCompletelyVisible
CALL CC WM_IsEnabled
CALL CC WM_IsFocussable
CALL CC WM_IsVisible
CALL CC WM_IsWindow
CALL CC WM_MakeModal
CALL CC WM_Move
CALL CC WM_MoveChildTo
CALL CC WM_NotifyParent
CALL CC WM_OnKey
CALL CC WM_Paint
CALL CC WM_PID__GetPrevState
CALL CC WM_ResizeWindow
CALL CC WM_Screen2Win
CALL CC WM_SendMessageNoPara
CALL CC WM_SendToParent
CALL CC WM_SetAnchor
CALL CC WM_SetCallback
CALL CC WM_SetCapture
CALL CC WM_SetCaptureMove
CALL CC WM_SetCreateFlags
CALL CC WM_SetDesktopColor
CALL CC WM_SetFocus
CALL CC WM_SetFocusOnNextChild
CALL CC WM_SetFocusOnPrevChild
CALL CC WM_SetId
CALL CC WM_SetpfPollPID
CALL CC WM_SetScrollbar
CALL CC WM_SetScrollState
CALL CC WM_SetSize
CALL CC WM_SetTrans
CALL CC WM_SetTransState
CALL CC WM_SetUserClipRect
CALL CC WM_SetXSize
CALL CC WM_SetYSize
CALL CC WM_Show
CALL CC WM_StayOnTop
CALL CC WM_Timer
CALL CC WM_TimerExternal
CALL CC WM_UserData
CALL CC WM_Validate
CALL CC WM_ValidateWindow
CALL CC WMMemDev
CALL CC WMTouch
